### PR TITLE
#207 - Simplified docker-compose and added support for testnet

### PR DESCRIPTION
**Pull request by thehenrytsai**
1. added `testnet` docker support
2. simplified docker-compose files, so now it is a one-command deployment
3. introduced the usage of ION docker images

Looking for people who are willing to test the new docker instructions before this is merged.

### CODE REVIEW

**Comment by monakaJP** [comment]
Hi, I tried this following readme.md. But readme.md's docker-compose version is old. I think it shold be changed "sudo curl -L https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose"

**Comment by thehenrytsai** [comment]
@monakaJP, thank you for trying out the `README.md`, I have updated the `curl` command based on your feedback. Were you able to progress further and run an ION node successfully?

**Comment by monakaJP** [comment]
@thehenrytsai Hi. it was succeeded on Ubuntu 20.04. DID can now be resolved.  If anything, a docker image for linux would be nice. I made it on dockerhub https://hub.docker.com/r/monakajp/ion/tags.

**Comment by thehenrytsai** [comment]
> a docker image for linux would be nice.

Hi @monakaJP, thanks for the fast response, I am not clear what you mean by a Linux docker image? The ION docker-image is already based off Linux (alpine), but I guess that’s not what you mean?

**Comment by monakaJP** [comment]
@thehenrytsai I'm sorry for I didn't explain. Maybe it is cpu architecture  problem. I failed to build it on x86_64 environment. So I build new image and used it. I thick we should add another architecture or how to build image.

**Comment by thehenrytsai** [comment]
@monakaJP, ah! This is my bad, I forgot that I am developing on a Macbook with M1 chip, as a result it built the ION image in arm64 architecture. Let me look into fixing this!

**Comment by thehenrytsai** [comment]
@monakaJP, I have updated the docker README and pushed a multi-platform ION image!

**Comment by monakaJP** [comment]
@thehenrytsai Great. Thank you for upgrade!

**Comment by thehenrytsai** [comment]
With today's commit, I think the PR is ready for final review and merge, will let this hang for a couple more days for more comments.

**Review by csuwildcat — APPROVED** [review]

**Pull request merged**
